### ISSUE TITLE
Wrong "Alias by" value

### ISSUE THREAD

**Issue by borisxm** [sraoss/grafana-sqldb-datasource#5]
It seems, that this plugin assigns wrong value to the alias field when more than one query placed on the graph and each query extracts data from its own table and field names in the both tables are the same. It simply duplicates value from the first query, so legend list same names, but actual numeric data displayed properly.

**Comment by mariosergioti** [comment]
Friend, what version of Grafana you using?

**Comment by borisxm** [comment]
This one: https://github.com/sraoss/grafana-sqldb-datasource/releases/download/V0.1/grafana-sqldb_20160615.tar.gz

**Comment by anzai** [comment]
I fixed the bug like this a few days ago. (commit: https://github.com/sraoss/grafana-sqldb-datasource/commit/faa405dbcb41e6d7ea8ed78627c806820d17f951)
Could you try it again with the latest frontend? But I haven't prepared the newer binary yet...

**Comment by borisxm** [comment]
Ok, pulled changes from the plugin repo, restarted Grafana and bug has gone. Thanks!
